#!/bin/bash

set -e

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

info "Adding services to registration file..."
REGISTRATION_FILE="internal/pkg/services/services.gen.go"
SERVICE_IF_FILE="internal/pkg/service-manager/service_manager.go"
SERVICE_IF_NAME="Service"
SERVICES_DIR="internal/pkg/services"
MODULE_NAME=$(head -n 1 go.mod | awk '{print $2}')

# Use gofindimpl to discover all service implementations
SERVICES_JSON=$(go tool gofindimpl \
    -interface ${SERVICE_IF_FILE}:${SERVICE_IF_NAME} \
    -dir ${SERVICES_DIR})

# Check if any services were found
SERVICE_COUNT=$(echo "$SERVICES_JSON" | jq length)
if [ "$SERVICE_COUNT" -eq 0 ]; then
    warning "No services found. Generating panic registration file..."
    cat > "$REGISTRATION_FILE" << EOF
// Code generated by service_registration.sh; DO NOT EDIT.

package services

func Init() {
	panic("No services")
}
EOF
    exit 0
fi

# Start generating the registration file
cat > "$REGISTRATION_FILE" << EOF
// Code generated by service_registration.sh; DO NOT EDIT.

package services

EOF

# Parse JSON and add imports, init function with factory registration
{
    echo "import ("
    echo "	servicemanager \"${MODULE_NAME}/internal/pkg/service-manager\""
    echo "$SERVICES_JSON" | jq -r '.[] | "\t" + .package + " \"" + .packagePath + "\""'
    echo ")"
    echo ""
    echo "func Init() {"
    echo "	sm := servicemanager.GetInstance()"
    echo ""
    echo "$SERVICES_JSON" | jq -r '.[] | "\tsm.Register(" + .package + ".ServiceName, func() (servicemanager.Service, error) {\n\t\treturn " + .package + ".New()\n\t})\n"'
    echo "}"
} >> "$REGISTRATION_FILE"

# Format the generated file and organize imports
go tool goimports -w "$REGISTRATION_FILE"

success "Services added to file at $REGISTRATION_FILE"
