// Code generated by regenerate_service_registration.sh; DO NOT EDIT.

package services

import helloworld "github.com/psyb0t/servicepack/internal/pkg/services/hello-world"

func init() { //nolint:gochecknoinits
	GetServiceManagerInstance().Add(
		helloworld.New(),
	)
}
