// Code generated by service_registration.sh; DO NOT EDIT.

package services

import (
	"log/slog"
	"os"
	"slices"
	"strings"

	servicemanager "github.com/psyb0t/servicepack/internal/pkg/service-manager"
	helloworld "github.com/psyb0t/servicepack/internal/pkg/services/hello-world"
)

const (
	envVarNameServicesEnabled = "SERVICES_ENABLED"
)

func Init() {
	sm := servicemanager.GetInstance()

	// Parse SERVICES_ENABLED env var
	servicesEnabledEnv := os.Getenv(envVarNameServicesEnabled)
	var enabledServices []string
	allEnabled := true

	if servicesEnabledEnv != "" {
		allEnabled = false

		for part := range strings.SplitSeq(servicesEnabledEnv, ",") {
			enabledServices = append(enabledServices, strings.TrimSpace(part))
		}
	}

	var service servicemanager.Service
	var err error

	if slices.Contains(enabledServices, helloworld.ServiceName) || allEnabled {
		service, err = helloworld.New()
		if err != nil {
			slog.Error("failed to create helloworld service", "error", err)
			os.Exit(1)
		}
		sm.Add(service)
	}

}
