#!/bin/bash

set -e

echo "Regenerating service registration file..."
REGISTRATION_FILE="internal/pkg/services/service_registration.gen.go"

# Use gofindimpl to discover all service implementations
SERVICES_JSON=$(go tool gofindimpl -interface internal/pkg/services/service_manager.go:Service -dir internal/pkg/services)

# Start generating the registration file
cat > "$REGISTRATION_FILE" << EOF
// Code generated by regenerate_service_registration.sh; DO NOT EDIT.

package services

EOF

# Parse JSON and add imports
echo "$SERVICES_JSON" | jq -r '.[] | "import " + .package + " \"" + .packagePath + "\""' >> "$REGISTRATION_FILE"

# Add the init function
cat >> "$REGISTRATION_FILE" << EOF

func init() { //nolint:gochecknoinits
	GetServiceManagerInstance().Add(
EOF

# Parse JSON and add service registrations
echo "$SERVICES_JSON" | jq -r '.[] | "\t\t" + .package + ".New(),"' >> "$REGISTRATION_FILE"

# Close the init function
cat >> "$REGISTRATION_FILE" << EOF
	)
}
EOF

echo "Service registration file regenerated at $REGISTRATION_FILE"