name: pipeline

on: [push]

jobs:
  call-go-workflow:
    uses: psyb0t/reusable-github-workflows/.github/workflows/go-workflow.yml@master
    with:
      go_version: "1.24.6"
      dep_command: "make dep"
      lint_command: "make lint"
      test_command: "make test-coverage"
